
CREATE TABLE IF NOT EXISTS client
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(255) NOT NULL,
    contact varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS car
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin varchar(255) NOT NULL,
    model varchar(255) NOT NULL,
    year int NOT NULL,
    mileage int NOT NULL,
    number varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS request
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem text NOT NULL,
    date date NOT NULL,
    response_name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS employee
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact varchar(255) NOT NULL,
    works text NOT NULL,
    consumables text NOT NULL
);

CREATE TABLE IF NOT EXISTS clients_dir
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(255) NOT NULL,
    telephone varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS nomenclature_dir
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    unit varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS work_dir
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    unit varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS employee_dir
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    telephone varchar(255) NOT NULL,
    passport  varchar(255) NOT NULL
);

-- DROP TABLE client;
-- DROP TABLE car;
-- DROP TABLE request;
-- DROP TABLE nomenclature_dir;
-- DROP TABLE work_dir;


INSERT INTO client(full_name, contact) VALUES ('Vasya', 88005553535);

SELECT * FROM client;
SELECT * FROM car;
SELECT * FROM request;
SELECT * FROM employee;
SELECT * FROM clients_dir;
SELECT * FROM nomenclature_dir;
SELECT * FROM work_dir;
SELECT * FROM employee_dir;


