DROP TABLE client;

CREATE TABLE IF NOT EXISTS client
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(255) NOT NULL,
    contact varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS car
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin varchar(255) NOT NULL,
    model varchar(255) NOT NULL,
    year int NOT NULL,
    mileage int NOT NULL,
    number varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS request
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem text NOT NULL,
    date date NOT NULL,
    response_name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS employee
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact varchar(255) NOT NULL,
    works text NOT NULL,
    consumables text NOT NULL
);

DROP TABLE client;
DROP TABLE car;
DROP TABLE request;


SELECT * FROM client;
SELECT * FROM car;
SELECT * FROM request;
SELECT * FROM employee;


